// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

///<<< BEGIN WRITING YOUR CODE FILE_INIT
using UnityEngine;
///<<< END WRITING YOUR CODE

public class AgentBase : behaviac.Agent
///<<< BEGIN WRITING YOUR CODE AgentBase
///<<< END WRITING YOUR CODE
{
	public float attackFlySpeed = 0f;

	public float attackFreq = 0f;

	public float attackValueDistant = 0f;

	public float attackValueNear = 0f;

	public float dashDistance = 0f;

	public float moveSpeed = 0f;

	public float rotateSpeed = 0f;

	public void GetHit(int color, float value, int typeOfAttack)
	{
///<<< BEGIN WRITING YOUR CODE GetHit
///<<< END WRITING YOUR CODE
	}

	public void Move()
	{
///<<< BEGIN WRITING YOUR CODE Move
///<<< END WRITING YOUR CODE
	}

	public void SayHello()
	{
///<<< BEGIN WRITING YOUR CODE SayHello
		Debug.Log("Engine");
///<<< END WRITING YOUR CODE
	}

	public void SayMyName()
	{
///<<< BEGIN WRITING YOUR CODE SayMyName
///<<< END WRITING YOUR CODE
	}

///<<< BEGIN WRITING YOUR CODE CLASS_PART
	public CBehaviour behaviour;
///<<< END WRITING YOUR CODE

}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

