// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: ../shpkng/Documents/Neon_3rd/Assets/Scripts/behaviac/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: FirstBT

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_FirstBT_node0 : behaviac.Action
	{
		public Action_bt_FirstBT_node0()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((AgentBase)pAgent).SayHello();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_FirstBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("FirstBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("BossAgent");
#endif
			// children
			{
				Action_bt_FirstBT_node0 node0 = new Action_bt_FirstBT_node0();
				node0.SetClassNameString("Action");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("BossAgent");
#endif
				bt.AddChild(node0);
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

}
